"use client";
import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { BottomActionBar, useBottomActionBarSpacer } from "@/components/ui/bottom-action-bar";
import { HelpHint } from "@/components/ui/help-hint";
import { Input } from "@/components/ui/input";
import { QuickChips } from "@/components/ui/quick-chips";
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Stepper } from "@/components/ui/stepper";
import { ApiClientError, apiData, apiFetch } from "@/lib/api/client";
import { REMINDER_KINDS, type CalendarReminderRow, type CalendarReminderUpsert, type GoogleCalendarStatus, type HelpTooltipMap, type ReminderKind, type RemindersResponse } from "@/types/database";

const config:Record<ReminderKind,{title:string;description:string}>={treino:{title:"Hora do treino",description:"Mantenha consistência nos dias escolhidos."},refeicoes:{title:"Registrar refeições",description:"Não deixe as refeições passarem sem registro."},agua:{title:"Beber água",description:"Uma pausa para cuidar da hidratação."},pesagem:{title:"Pesagem",description:"Acompanhe a tendência sem pressão diária."},medicacao:{title:"Aplicação da medicação",description:"Lembrete no dia da dose prescrita pelo seu médico."}};
const days=["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"];
const times=["07:00","08:00","12:00","19:00","21:00"];
function toMinutes(time:string){const [h,m]=time.split(":").map(Number);return h*60+m;}
function toTime(minutes:number){return `${String(Math.floor(minutes/60)).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`;}
function valuesFor(kind:ReminderKind, data:RemindersResponse):CalendarReminderUpsert {const row=data.reminders.find(r=>r.kind===kind);return {title:row?.title??config[kind].title,days_of_week:row?.days_of_week??[1,2,3,4,5],local_time:row?.local_time.slice(0,5)??"08:00",duration_minutes:row?.duration_minutes??30,is_active:row?.is_active??true};}
const sheet="rounded-t-3xl border-glass-border bg-surface-solid p-5";
export function RemindersDashboard({googleResult,googleReason}:{googleResult?:string;googleReason?:string}){
  const [data,setData]=useState<RemindersResponse>();const [help,setHelp]=useState<Partial<HelpTooltipMap>>({});const [selected,setSelected]=useState<ReminderKind>("medicacao");
  const [values,setValues]=useState<CalendarReminderUpsert>();const [error,setError]=useState("");const [message,setMessage]=useState(googleResult==="connected"?"Google Agenda conectado.":googleResult==="erro"?`Não foi possível conectar ao Google${googleReason?` (${googleReason})`:""}.`:"");
  const [pending,setPending]=useState(false);const [confirm,setConfirm]=useState<"remove"|"disconnect">();const spacer=useBottomActionBarSpacer();
  const load=useCallback(async()=>{try{const r=await apiFetch<RemindersResponse>("/api/reminders");setData(r.data);setValues(valuesFor("medicacao",r.data));setHelp(r.help??{});}catch(e){setError(e instanceof Error?e.message:"Lembretes indisponíveis.");}},[]);
  useEffect(()=>{const id=setTimeout(()=>{void load();if(googleResult)window.history.replaceState({},"","/lembretes");},0);return()=>clearTimeout(id);},[load,googleResult]);
  const row=data?.reminders.find(r=>r.kind===selected);
  async function save(){if(!values)return;setPending(true);setError("");try{const saved=await apiData<CalendarReminderRow>(`/api/reminders/${selected}`,{method:"PUT",json:values});setData(v=>v?{...v,reminders:[...v.reminders.filter(r=>r.kind!==selected),saved]}:v);setMessage("Lembrete salvo e sincronizado.");}catch(e){if(e instanceof ApiClientError&&e.status===502){setMessage("Salvo, mas o Google não respondeu. Tente sincronizar novamente.");void load();}else if(e instanceof ApiClientError&&e.status===409){setData(v=>v?{...v,google:{...v.google,connected:false,google_email:null}}:v);setMessage("A conexão com o Google expirou. Reconecte para sincronizar.");}else setError(e instanceof Error?e.message:"Não foi possível salvar.");}finally{setPending(false);}}
  async function remove(){setPending(true);try{await apiData(`/api/reminders/${selected}`,{method:"DELETE"});setData(v=>v?{...v,reminders:v.reminders.filter(r=>r.kind!==selected)}:v);setMessage("Lembrete removido.");setValues({title:config[selected].title,days_of_week:[1,2,3,4,5],local_time:"08:00",duration_minutes:30,is_active:true});setConfirm(undefined);}catch(e){setError(e instanceof Error?e.message:"Não foi possível remover.");}finally{setPending(false);}}
  async function disconnect(){setPending(true);try{const google=await apiData<GoogleCalendarStatus>("/api/integrations/google",{method:"DELETE"});setData(v=>v?{...v,google}:v);setMessage("Google Agenda desconectado.");setConfirm(undefined);}catch(e){setError(e instanceof Error?e.message:"Não foi possível desconectar.");}finally{setPending(false);}}
  return <div className={`mx-auto max-w-2xl space-y-5 ${spacer}`}><header><p className="text-xs font-semibold uppercase tracking-widest text-brand-strong">Sua rotina no celular</p><h1 className="mt-1 text-3xl font-black">Lembretes</h1><p className="mt-2 text-sm text-text-secondary">Receba avisos nos horários que funcionam para você.</p></header>
    {message?<p role="status" className="rounded-xl bg-success-500/10 p-3 text-sm text-success">{message}</p>:null}{error?<p role="alert" className="rounded-xl bg-danger-500/10 p-3 text-sm text-danger">{error}</p>:null}
    {data?<><section className="rounded-2xl border border-glass-border bg-glass p-4"><h2 className="font-semibold">{data.google.connected?"Google Agenda conectado":"Conecte o Google Agenda"}</h2><p className="mt-1 text-sm text-text-secondary">{data.google.connected?data.google.google_email:"Receba os lembretes diretamente no celular."}</p>{data.google.connected?<Button variant="outline" className="mt-3 min-h-11" onClick={()=>setConfirm("disconnect")}>Desconectar</Button>:data.google.available?<Button asChild className="mt-3 min-h-11"><a href="/api/integrations/google/connect">Conectar Google</a></Button>:null}</section>
    <div className="grid gap-2 sm:grid-cols-2">{REMINDER_KINDS.map(kind=><button key={kind} onClick={()=>{setSelected(kind);setValues(valuesFor(kind,data));}} className={`min-h-16 rounded-xl border p-3 text-left ${selected===kind?"border-success-500 bg-success-500/10":"border-glass-border bg-glass"}`}><strong className="block text-sm">{config[kind].title}</strong><span className="text-xs text-text-secondary">{data.reminders.some(r=>r.kind===kind)?"Configurado":"Configurar"}</span></button>)}</div>
    {values?<section className="space-y-5 rounded-2xl border border-glass-border bg-glass p-5"><div><div className="flex items-center"><h2 className="font-bold">{config[selected].title}</h2><HelpHint help={help["calendar_reminders.kind"]}/></div><p className="text-sm text-text-secondary">{config[selected].description}</p></div><div><label htmlFor="reminder-title" className="text-sm font-medium">Título</label><Input id="reminder-title" value={values.title} onChange={e=>setValues(v=>v?{...v,title:e.target.value}:v)} className="mt-2 min-h-11"/></div><div><p className="text-sm font-medium">Dias da semana</p><div className="mt-2 grid grid-cols-7 gap-1">{days.map((label,day)=><button key={day} aria-pressed={values.days_of_week.includes(day)} onClick={()=>setValues(v=>v?{...v,days_of_week:v.days_of_week.includes(day)?v.days_of_week.filter(d=>d!==day):[...v.days_of_week,day].sort()}:v)} className={`min-h-11 rounded-lg border text-xs ${values.days_of_week.includes(day)?"border-success-500 bg-success-500/20 text-success":"border-glass-border text-text-secondary"}`}>{label}</button>)}</div></div><div><p className="mb-2 text-sm font-medium">Horário</p><QuickChips options={times.map(value=>({value,label:value}))} onPick={value=>setValues(v=>v?{...v,local_time:value}:v)}/><Stepper className="mt-3" label="Ajustar horário" value={toMinutes(values.local_time)} onChange={n=>setValues(v=>v?{...v,local_time:toTime(n)}:v)} step={15} min={0} max={1425} format={toTime}/></div><Stepper label="Duração do evento" value={values.duration_minutes??30} onChange={n=>setValues(v=>v?{...v,duration_minutes:n}:v)} step={5} min={5} max={240} unit="min"/><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" className="size-5 accent-emerald-500" checked={values.is_active??true} onChange={e=>setValues(v=>v?{...v,is_active:e.target.checked}:v)}/>Lembrete ativo</label>{row?<Button variant="outline" className="min-h-11 text-danger" onClick={()=>setConfirm("remove")}>Remover lembrete</Button>:null}</section>:null}
    <BottomActionBar><Button data-primary-action="save-reminder" className="h-12 w-full bg-success-500 font-bold text-on-bright hover:bg-success-500/85" disabled={pending||!values} onClick={()=>void save()}>{pending?"Salvando…":"Salvar lembrete"}</Button></BottomActionBar></>:<p className="text-sm text-text-secondary">Carregando lembretes…</p>}
    <Sheet open={!!confirm} onOpenChange={v=>{if(!v)setConfirm(undefined);}}><SheetContent side="bottom" className={sheet}><SheetHeader className="px-0"><SheetTitle>{confirm==="remove"?"Remover lembrete?":"Desconectar Google Agenda?"}</SheetTitle><SheetDescription>{confirm==="remove"?"Este evento será removido da sua agenda.":"Os eventos sincronizados serão removidos."}</SheetDescription></SheetHeader><SheetFooter className="px-0"><Button variant="outline" onClick={()=>setConfirm(undefined)}>Cancelar</Button><Button variant="destructive" disabled={pending} onClick={()=>void (confirm==="remove"?remove():disconnect())}>Confirmar</Button></SheetFooter></SheetContent></Sheet>
  </div>;
}
