"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { BottomActionBar, useBottomActionBarSpacer } from "@/components/ui/bottom-action-bar";
import { HelpHint } from "@/components/ui/help-hint";
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Stepper } from "@/components/ui/stepper";
import { Textarea } from "@/components/ui/textarea";
import { apiData, apiFetch, newClientId } from "@/lib/api/client";
import { getTodayIsoDate } from "@/lib/date";
import { WORKOUT_GOALS, WORKOUT_LEVELS, WORKOUT_LOCATIONS, type HelpTooltipMap, type ProgramDetail, type ProgramExerciseRow, type ProgramWorkoutLogInsert, type TrainingToday, type WorkoutProgramRow } from "@/types/database";

const goals: Record<string,string> = { emagrecimento:"Emagrecimento", hipertrofia:"Ganho de massa", condicionamento:"Condicionamento", corrida:"Corrida", iniciante:"Começar", mobilidade:"Mobilidade" };
const levels: Record<string,string> = { iniciante:"Iniciante", intermediario:"Intermediário", avancado:"Avançado" };
const locations: Record<string,string> = { academia:"Academia", casa:"Casa", ar_livre:"Ar livre" };
const sheet = "max-h-[94dvh] overflow-y-auto rounded-t-3xl border-glass-border bg-surface-solid p-5 pb-[max(1rem,env(safe-area-inset-bottom))] sm:left-1/2 sm:max-w-xl sm:-translate-x-1/2";
const action = "h-12 w-full bg-success-500 font-bold text-on-bright hover:bg-success-500/85";
const duration = (seconds:number) => seconds >= 60 ? `${Math.round(seconds/60)} min` : `${seconds} s`;
function ExerciseList({ exercises }: { exercises: ProgramExerciseRow[] }) { return <ul className="mt-3 space-y-2 text-sm text-text-secondary">{exercises.map((e) => <li key={e.id} className="border-t border-glass-border pt-2"><strong className="text-foreground">{e.name}</strong><span className="block">{e.sets ? `${e.sets} séries` : ""}{e.reps ? ` × ${e.reps}` : ""}{e.duration_seconds ? ` · ${duration(e.duration_seconds)}` : ""}{e.rest_seconds ? ` · descanso ${duration(e.rest_seconds)}` : ""}{e.distance_m ? ` · ${e.distance_m} m` : ""}</span>{e.intensity ? <span className="block">Intensidade: {e.intensity}</span> : null}{e.notes ? <span className="block">{e.notes}</span> : null}</li>)}</ul>; }

export function TrainingDashboard() {
  const [today,setToday] = useState<TrainingToday>(); const [programs,setPrograms] = useState<WorkoutProgramRow[]>([]); const [detail,setDetail] = useState<ProgramDetail>();
  const [goal,setGoal] = useState(""); const [level,setLevel] = useState(""); const [location,setLocation] = useState("");
  const [executing,setExecuting] = useState(false); const [finishing,setFinishing] = useState(false); const [confirmSwitch,setConfirmSwitch] = useState(false);
  const [done,setDone] = useState<Record<string,number>>({}); const [elapsed,setElapsed] = useState<Record<string,number>>({}); const [running,setRunning] = useState<string>(); const [rest,setRest] = useState(0);
  const [minutes,setMinutes] = useState(30); const [effort,setEffort] = useState<1|2|3|4|5>(3); const [notes,setNotes] = useState("");
  const [help,setHelp] = useState<Partial<HelpTooltipMap>>({}); const [busy,setBusy] = useState(false); const [error,setError] = useState("");
  const spacer = useBottomActionBarSpacer();
  const load = useCallback(async () => { try { const response = await apiFetch<TrainingToday>("/api/training/today"); setToday(response.data); setHelp(response.help ?? {}); } catch(cause) { setError(cause instanceof Error ? cause.message : "Treinos indisponíveis."); } }, []);
  useEffect(() => { const id = setTimeout(() => void load(),0); return () => clearTimeout(id); },[load]);
  useEffect(() => { if (today?.enrollment) return; const p = new URLSearchParams(); if(goal)p.set("goal",goal); if(level)p.set("level",level); if(location)p.set("location",location); let active=true; void apiData<WorkoutProgramRow[]>(`/api/training/programs?${p}`).then(v => {if(active)setPrograms(v);}).catch(e => {if(active)setError(e instanceof Error?e.message:"Catálogo indisponível.");}); return () => {active=false;}; },[today?.enrollment,goal,level,location]);
  useEffect(() => { if(!today?.program)return; let active=true; void apiData<ProgramDetail>(`/api/training/programs/${today.program.slug}`).then(v => {if(active)setDetail(v);}).catch(() => {}); return () => {active=false;}; },[today?.program]);
  useEffect(() => { if(!running && !rest)return; const id=setInterval(() => { if(running)setElapsed(v=>({...v,[running]:(v[running]??0)+1})); setRest(v=>Math.max(0,v-1)); },1000); return () => clearInterval(id); },[running,rest]);
  async function openDetail(slug:string) { try {setDetail(await apiData<ProgramDetail>(`/api/training/programs/${slug}`));}catch(e){setError(e instanceof Error?e.message:"Detalhes indisponíveis.");} }
  async function enroll(id:string) {setBusy(true); try {setToday(await apiData<TrainingToday>("/api/training/enrollment",{method:"POST",json:{program_id:id}}));setDetail(undefined);}catch(e){setError(e instanceof Error?e.message:"Não foi possível começar.");}finally{setBusy(false);} }
  async function leave() {setBusy(true);try{setToday(await apiData<TrainingToday>("/api/training/enrollment",{method:"DELETE"}));setDetail(undefined);setConfirmSwitch(false);}catch(e){setError(e instanceof Error?e.message:"Não foi possível trocar.");}finally{setBusy(false);} }
  async function finish() {const workout=today?.next_workout;if(!workout)return;setBusy(true);setError("");const payload:ProgramWorkoutLogInsert={id:newClientId(),program_workout_id:workout.id,performed_on:getTodayIsoDate(),duration_minutes:minutes,effort,notes:notes.trim()||null,exercise_results:workout.exercises.map(e=>({exercise_id:e.id,sets_done:done[e.id]??0}))};try{setToday(await apiData<TrainingToday>("/api/training/logs",{method:"POST",json:payload}));setFinishing(false);setExecuting(false);setDone({});setNotes("");setElapsed({});setRest(0);}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar.");}finally{setBusy(false);} }
  const workout=today?.next_workout;
  return <div className={`mx-auto max-w-2xl space-y-5 ${spacer}`}>
    <header><p className="text-xs font-semibold uppercase tracking-widest text-brand-strong">Seu movimento</p><div className="flex items-center gap-2"><h1 className="mt-1 text-3xl font-black">Treinos</h1><HelpHint help={help["route.treinos"]}/></div><p className="mt-2 text-sm text-text-secondary">Escolha um caminho e avance no seu ritmo.</p></header>
    {error?<p role="alert" className="rounded-xl bg-danger-500/15 p-3 text-sm text-danger">{error}</p>:null}
    {!today?<p className="text-sm text-text-secondary">Carregando treinos…</p>:!today.enrollment?<div className="space-y-4">
      {([[goal,setGoal,WORKOUT_GOALS,goals],[location,setLocation,WORKOUT_LOCATIONS,locations],[level,setLevel,WORKOUT_LEVELS,levels]] as const).map(([value,change,options,names],index)=><div key={index} className="flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><button className={`min-h-11 shrink-0 rounded-full border px-4 text-sm ${!value?"border-success-500 text-success":"border-glass-border text-foreground"}`} onClick={()=>change("")}>Todos</button>{options.map(o=><button key={o} className={`min-h-11 shrink-0 rounded-full border px-4 text-sm ${value===o?"border-success-500 bg-success-500/15 text-success":"border-glass-border text-foreground"}`} onClick={()=>change(o)}>{names[o]}</button>)}</div>)}
      {programs.map(p=><button key={p.id} onClick={()=>void openDetail(p.slug)} className="w-full rounded-2xl border border-glass-border bg-glass p-5 text-left"><h2 className="text-lg font-bold">{p.title}</h2><p className="mt-2 text-sm text-text-secondary">{p.summary}</p><div className="mt-3 flex flex-wrap gap-2">{[goals[p.goal],levels[p.level],locations[p.location],`${p.days_per_week} dias/semana`,p.session_minutes?`${p.session_minutes} min/sessão`:null,p.duration_weeks?`${p.duration_weeks} semanas`:null].filter(Boolean).map(label=><span key={label} className="rounded-full bg-glass px-2.5 py-1 text-xs text-foreground">{label}</span>)}</div></button>)}
      {!programs.length?<p className="text-sm text-text-secondary">Nenhum programa encontrado. Ajuste os filtros.</p>:null}
    </div>:<div className="space-y-4">
      <section className="rounded-2xl border border-glass-border bg-glass p-5"><p className="text-xs font-semibold uppercase text-brand-strong">Programa ativo</p><h2 className="mt-1 text-xl font-bold">{today.program?.title}</h2>{today.program_completed?<div className="mt-4 rounded-xl bg-success-500/15 p-4 text-success"><strong>Programa concluído!</strong><p className="mt-1 text-sm">Você completou {today.completed_count} treinos. Escolha o próximo desafio.</p></div>:<><p className="mt-3 text-sm text-text-secondary">{today.total_sessions?`${today.completed_count} de ${today.total_sessions} treinos`:`${today.completed_count} treinos feitos`}</p>{today.total_sessions?<div role="progressbar" aria-valuenow={today.completed_count} aria-valuemax={today.total_sessions} className="mt-2 h-2 rounded-full bg-glass"><div className="h-full rounded-full bg-success-500" style={{width:`${Math.min(100,100*today.completed_count/today.total_sessions)}%`}}/></div>:null}{today.done_today?<p className="mt-3 rounded-full bg-success-500/15 px-3 py-2 text-sm font-semibold text-success">Treino de hoje feito</p>:null}</>}</section>
      {workout?<section className="rounded-2xl border border-glass-border bg-glass p-5"><p className="text-xs font-semibold uppercase text-text-secondary">Próximo treino</p><h2 className="mt-2 text-xl font-bold">{workout.title}</h2><p className="mt-1 text-sm text-text-secondary">{workout.focus??"Avance uma sessão"} · {workout.estimated_minutes??today.program?.session_minutes??30} min</p><ul className="mt-4 space-y-2 text-sm text-foreground">{workout.exercises.map(e=><li key={e.id}>• {e.name}</li>)}</ul></section>:null}
      <button className="min-h-11 text-sm text-text-secondary underline" onClick={()=>setConfirmSwitch(true)}>Trocar de programa</button>
      {today.recent_logs.length?<section className="rounded-2xl border border-glass-border bg-glass p-5"><h2 className="font-bold">Histórico recente</h2><ul className="mt-3 divide-y divide-white/10">{today.recent_logs.map(log=><li key={log.id} className="py-3 text-sm text-text-secondary">{new Intl.DateTimeFormat("pt-BR").format(new Date(`${log.performed_on}T12:00:00`))} · {detail?.workouts.find(w=>w.id===log.program_workout_id)?.title??"Treino"} · esforço {log.effort??"—"}/5 · {log.duration_minutes??"—"} min</li>)}</ul></section>:null}
    </div>}
    <Link href="/treinos/meu-plano" className="block min-h-11 pt-3 text-sm text-text-secondary underline">Meu plano personalizado</Link>
    {today&&!today.enrollment&&programs.length?<BottomActionBar><Button data-primary-action="enroll" className={action} onClick={()=>void openDetail(programs[0].slug)}>Ver primeiro programa</Button></BottomActionBar>:null}
    {today?.enrollment&&(workout||today.program_completed)?<BottomActionBar><Button data-primary-action={workout?"finish-workout":"enroll"} className={action} onClick={()=>{if(workout){setMinutes(workout.estimated_minutes??30);setExecuting(true);}else void leave();}}>{workout?"Iniciar próximo treino":"Escolher outro programa"}</Button></BottomActionBar>:null}
    <Sheet open={!!detail&&!today?.enrollment} onOpenChange={v=>{if(!v)setDetail(undefined);}}><SheetContent side="bottom" className={sheet}><SheetHeader className="px-0"><SheetTitle className="text-xl">{detail?.program.title}</SheetTitle><SheetDescription>{detail?.program.description??detail?.program.summary}</SheetDescription></SheetHeader><div className="space-y-4">{detail?.workouts.map(w=><div key={w.id} className="rounded-xl border border-glass-border p-4"><h3 className="font-semibold">{w.title}</h3><p className="mt-1 text-sm text-text-secondary">{w.focus} · {w.estimated_minutes??detail.program.session_minutes??30} min</p><ExerciseList exercises={w.exercises}/></div>)}</div><SheetFooter className="sticky bottom-0 -mx-5 bg-surface-solid px-5"><Button data-primary-action="enroll" className={action} disabled={busy} onClick={()=>detail&&void enroll(detail.program.id)}>Começar este programa</Button></SheetFooter></SheetContent></Sheet>
    <Sheet open={executing} onOpenChange={setExecuting}><SheetContent side="bottom" className={sheet}><SheetHeader className="px-0"><SheetTitle>{workout?.title}</SheetTitle><SheetDescription>Marque as séries concluídas e avance no seu ritmo.</SheetDescription></SheetHeader><div className="space-y-3">{workout?.exercises.map(e=><div key={e.id} className="rounded-xl border border-glass-border p-4"><h3 className="font-semibold">{e.name}</h3><p className="text-sm text-text-secondary">{e.sets?`${e.sets} séries`:""}{e.reps?` × ${e.reps}`:""}{e.duration_seconds?` · ${duration(e.duration_seconds)}`:""}</p><div className="mt-2 flex flex-wrap gap-2">{Array.from({length:e.sets??1},(_,i)=><button key={i} aria-pressed={(done[e.id]??0)>i} className={`min-h-11 rounded-xl border px-4 text-sm ${(done[e.id]??0)>i?"border-success-500 bg-success-500/20 text-success":"border-glass-border"}`} onClick={()=>{setDone(v=>({...v,[e.id]:Math.max(v[e.id]??0,i+1)}));setRest(e.rest_seconds??0);}}>Série {i+1} {(done[e.id]??0)>i?"✓":""}</button>)}</div>{e.duration_seconds?<button className="mt-3 min-h-11 text-sm text-success" onClick={()=>setRunning(running===e.id?undefined:e.id)}>{running===e.id?"Pausar":"Iniciar"} cronômetro · {duration(elapsed[e.id]??0)}</button>:null}{e.rest_seconds?<p className="mt-2 text-xs text-text-secondary">Descanso: {rest?`${rest} s restantes`:`${duration(e.rest_seconds)} entre séries`}</p>:null}</div>)}</div><SheetFooter className="sticky bottom-0 -mx-5 bg-surface-solid px-5"><Button data-primary-action="finish-workout" className={action} onClick={()=>{setRunning(undefined);setExecuting(false);setFinishing(true);}}>Concluir treino</Button></SheetFooter></SheetContent></Sheet>
    <Sheet open={finishing} onOpenChange={setFinishing}><SheetContent side="bottom" className={sheet}><SheetHeader className="px-0"><SheetTitle>Concluir treino</SheetTitle><SheetDescription>Como foi sua sessão?</SheetDescription></SheetHeader><Stepper label="Duração" value={minutes} onChange={setMinutes} step={5} min={5} max={600} unit="min"/><div><div className="flex items-center"><p className="text-sm font-medium">Esforço</p><HelpHint help={help["program_workout_logs.effort"]}/></div><div className="grid grid-cols-5 gap-2">{([1,2,3,4,5] as const).map(n=><button key={n} aria-pressed={effort===n} className={`min-h-11 rounded-xl border ${effort===n?"border-success-500 bg-success-500/20 text-success":"border-glass-border"}`} onClick={()=>setEffort(n)}>{n}</button>)}</div></div><details><summary className="min-h-11 cursor-pointer text-sm">Notas opcionais</summary><Textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={1000} rows={3}/></details>{error?<p role="alert" className="text-sm text-danger">{error}</p>:null}<SheetFooter className="sticky bottom-0 -mx-5 bg-surface-solid px-5"><Button data-primary-action="finish-workout" className={action} disabled={busy} onClick={()=>void finish()}>{busy?"Salvando…":"Salvar treino"}</Button></SheetFooter></SheetContent></Sheet>
    <Sheet open={confirmSwitch} onOpenChange={setConfirmSwitch}><SheetContent side="bottom" className={sheet}><SheetHeader className="px-0"><SheetTitle>Trocar de programa?</SheetTitle><SheetDescription>Seu histórico fica salvo. Você poderá escolher outro programa.</SheetDescription></SheetHeader><SheetFooter className="px-0"><Button variant="outline" className="h-11" onClick={()=>setConfirmSwitch(false)}>Continuar neste programa</Button><Button className="h-11 bg-danger-500 text-on-brand" disabled={busy} onClick={()=>void leave()}>Sair e escolher outro</Button></SheetFooter></SheetContent></Sheet>
  </div>;
}
