"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { HelpHint } from "@/components/ui/help-hint";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { apiFetch } from "@/lib/api/client";
import { TIP_CATEGORIES, type HelpTooltipMap, type TipCategory, type TipRow } from "@/types/database";
export const tipNames:Record<TipCategory,string>={alimentacao:"Alimentação",treino:"Treino",medicacao:"Medicação",mentalidade:"Mentalidade",comunidade:"Comunidade",app:"Como usar o app"};
export function TipsBrowser(){
  const [category,setCategory]=useState<TipCategory| "">(""); const [tips,setTips]=useState<TipRow[]>([]); const [selected,setSelected]=useState<TipRow>(); const [error,setError]=useState(""); const [help,setHelp]=useState<Partial<HelpTooltipMap>>({});
  useEffect(()=>{let active=true;void apiFetch<TipRow[]>(`/api/tips${category?`?category=${category}`:""}`).then(response=>{if(!active)return;const rows=response.data;setTips(rows);setHelp(response.help??{});const direct=new URLSearchParams(window.location.search).get("tip");if(direct)setSelected(rows.find(row=>row.id===direct));}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Não foi possível carregar as dicas.");});return()=>{active=false;};},[category]);
  return <div className="mx-auto max-w-2xl space-y-5"><header><p className="text-xs font-semibold uppercase tracking-widest text-brand-strong">Mentoria para sua rotina</p><div className="flex items-center gap-2"><h1 className="mt-1 text-3xl font-black">Dicas</h1><HelpHint help={help["route.dicas"]}/></div><p className="mt-2 text-sm text-text-secondary">Ideias curtas para colocar em prática.</p></header>
    <div className="flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><button onClick={()=>setCategory("")} className={`min-h-11 shrink-0 rounded-full border px-4 text-sm ${!category?"border-success-500 bg-success-500/15 text-success":"border-glass-border text-foreground"}`}>Todas</button>{TIP_CATEGORIES.map(c=><button key={c} onClick={()=>setCategory(c)} className={`min-h-11 shrink-0 rounded-full border px-4 text-sm ${category===c?"border-success-500 bg-success-500/15 text-success":"border-glass-border text-foreground"}`}>{tipNames[c]}</button>)}</div>
    {error?<p role="alert" className="text-sm text-danger">{error}</p>:null}{tips.map(t=><button key={t.id} onClick={()=>setSelected(t)} className="w-full rounded-2xl border border-glass-border bg-glass p-5 text-left"><span className="text-xs font-semibold uppercase text-success">{tipNames[t.category]}</span><h2 className="mt-2 text-lg font-bold">{t.title}</h2><p className="mt-2 text-sm text-text-secondary">{t.read_minutes} min de leitura</p></button>)}{!tips.length&&!error?<p className="text-sm text-text-secondary">Ainda não há dicas nesta categoria.</p>:null}
    <Sheet open={!!selected} onOpenChange={v=>{if(!v)setSelected(undefined);}}><SheetContent side="bottom" className="max-h-[94dvh] overflow-y-auto rounded-t-3xl border-glass-border bg-surface-solid p-6 sm:left-1/2 sm:max-w-2xl sm:-translate-x-1/2"><SheetHeader className="px-0"><p className="text-xs font-semibold uppercase text-success">{selected?tipNames[selected.category]:""}</p><SheetTitle className="max-w-prose text-2xl font-bold">{selected?.title}</SheetTitle><SheetDescription>{selected?.read_minutes} min de leitura</SheetDescription></SheetHeader><div className="mx-auto max-w-[65ch] whitespace-pre-wrap text-base leading-8 text-foreground">{selected?.body}</div><Button variant="outline" className="min-h-11" onClick={()=>setSelected(undefined)}>Fechar leitura</Button></SheetContent></Sheet>
  </div>;
}
