import Link from "next/link";
import { HelpHint } from "@/components/ui/help-hint";
import type { HelpTooltipMap, NutritionMetrics } from "@/types/database";
const MACROS = [{ key: "protein_g", target: "protein_target_g", short: "P", label: "proteína" }, { key: "carbs_g", target: "carbs_target_g", short: "C", label: "carboidrato" }, { key: "fat_g", target: "fat_target_g", short: "G", label: "gordura" }] as const;
export function CalorieRemainingCard({ metrics, aboveFold, help }: { metrics: NutritionMetrics | null; aboveFold?: boolean; help?: Partial<HelpTooltipMap> }) {
  if (!metrics) return <section data-above-fold={aboveFold ? "kcal" : undefined} className="rounded-2xl border border-white/10 bg-white/10 p-4 shadow-xl backdrop-blur-md"><h2 className="text-lg font-bold">Defina suas metas</h2><p className="mt-1 text-sm text-zinc-300">Configure seu perfil para ver calorias e macros restantes.</p><Link href="/alimentacao" className="mt-3 inline-flex min-h-11 items-center rounded-xl bg-success-500 px-4 text-sm font-bold text-zinc-950">Configurar na Alimentação</Link></section>;
  const ratio = metrics.consumed_kcal / Math.max(metrics.recommended_kcal, 1);
  const tone = ratio > 1 ? "danger" : ratio >= 0.85 ? "warning" : "success";
  const color = tone === "danger" ? "var(--danger-500)" : tone === "warning" ? "var(--warning-500)" : "var(--success-500)";
  const percent = Math.min(100, Math.round(ratio * 100));
  return <section data-above-fold={aboveFold ? "kcal" : undefined} className="rounded-2xl border border-white/10 bg-white/10 p-4 shadow-xl backdrop-blur-md">
    <div className="flex items-center justify-between gap-4"><div className="min-w-0"><p className="text-sm font-semibold text-zinc-300">Calorias do dia</p><p className={`mt-0.5 text-2xl font-black tracking-tight ${tone === "danger" ? "text-danger-500" : tone === "warning" ? "text-warning-500" : "text-emerald-300"}`}>{metrics.remaining_kcal < 0 ? `Passou ${Math.abs(metrics.remaining_kcal)} kcal` : `Restam ${metrics.remaining_kcal} kcal`}</p><p className="mt-1 text-xs text-zinc-300">de {metrics.recommended_kcal} kcal no dia</p></div><div aria-label={`${percent}% da meta de calorias`} className="relative flex size-20 shrink-0 items-center justify-center rounded-full" style={{ background: `conic-gradient(${color} ${percent}%, rgba(255,255,255,.08) ${percent}% 100%)` }}><div className="flex size-16 items-center justify-center rounded-full bg-zinc-950 text-sm font-bold">{percent}%</div></div></div>
    <div className="mt-2 flex items-center gap-1"><span className="text-xs font-semibold text-zinc-200">Macros restantes</span><HelpHint help={help?.["metric.macros"]} /></div><div className="grid gap-2 sm:grid-cols-3">{MACROS.map((macro) => { const remaining = Math.max(0, Math.round(metrics[macro.target] - metrics[macro.key])); const macroPercent = Math.min(100, Math.round((metrics[macro.key] / Math.max(metrics[macro.target], 1)) * 100)); return <div key={macro.key}><div className="mb-1 flex justify-between gap-2 text-xs text-zinc-300"><span>{macro.short}</span><span className="truncate">faltam {remaining} g de {macro.label}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-success-500" style={{ width: `${macroPercent}%` }} /></div></div>; })}</div>
  </section>;
}
