"use client";
import { useCallback, useEffect, useState, type ReactNode } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Droplet, HeartPulse, LoaderCircle, Plus, Scale, Utensils } from "lucide-react";
import { CalorieRemainingCard } from "@/components/alimentacao/calorie-remaining-card";
import { MealEditor, MEAL_LABELS, type MealEditing } from "@/components/alimentacao/meal-editor";
import { WeightSheet } from "@/components/alimentacao/weight-sheet";
import { MedicationLogSheet, SEVERE_NOTICE } from "@/components/saude/medication-log-sheet";
import { BottomActionBar, useBottomActionBarSpacer } from "@/components/ui/bottom-action-bar";
import { Button } from "@/components/ui/button";
import { apiData, apiFetch, newClientId } from "@/lib/api/client";
import { MEDICATION_DISCLAIMER, type DashboardSummary, type HelpTooltipMap, type MedicationOverview, type MedicationsResponse, type TrainingToday, type WaterLogInsert, type WaterLogRow, type WeightLogRow } from "@/types/database";
function greeting(time: string) { const hour = Number(time.slice(0, 2)); return hour < 12 ? "Bom dia" : hour < 18 ? "Boa tarde" : "Boa noite"; }
function shortDate(date: string) { return new Intl.DateTimeFormat("pt-BR", { weekday: "short", day: "2-digit", month: "short", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`)); }
function actionText(summary: DashboardSummary) { const action = summary.next_action; if (action.kind === "setup_profile") return "Configure suas metas (2 min)"; if (action.kind === "log_meal") return `Registrar ${MEAL_LABELS[action.meal_slot]}${action.overdue ? " · atrasado" : ""}`; if (action.kind === "drink_water") return `Beber ${action.suggested_ml} ml — você está ${action.behind_ml} ml atrás do ritmo`; if (action.kind === "log_weight") return "Registrar peso da semana"; if (action.kind === "log_medication") return `Hoje é dia de ${action.name}`; return "Tudo em dia"; }
export function DashboardExperience({ userId, masterCards }: { userId: string; masterCards: ReactNode }) {
  const router = useRouter(); const spacer = useBottomActionBarSpacer();
  const [summary, setSummary] = useState<DashboardSummary>(); const [training, setTraining] = useState<TrainingToday>(); const [error, setError] = useState<string>(); const [pending, setPending] = useState(false);
  const [editing, setEditing] = useState<MealEditing>(); const [weightOpen, setWeightOpen] = useState(false);
  const [medication, setMedication] = useState<MedicationOverview | null>(null); const [medHelp, setMedHelp] = useState<Partial<HelpTooltipMap>>({}); const [foodHelp, setFoodHelp] = useState<Partial<HelpTooltipMap>>({}); const [strongNotice, setStrongNotice] = useState(false); const [medSevere, setMedSevere] = useState(false);
  const [toast, setToast] = useState<{ message: string; undo?: () => void }>();
  const load = useCallback(async () => { try { const [daily, workout] = await Promise.all([apiFetch<DashboardSummary>("/api/dashboard/summary"), apiFetch<TrainingToday>("/api/training/today")]); setSummary(daily.data); setTraining(workout.data); setError(undefined); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar o resumo."); } }, []);
  useEffect(() => { const id = setTimeout(() => void load(), 0); apiFetch("/api/foods?q=").then((result) => setFoodHelp(result.help ?? {})).catch(() => {}); return () => clearTimeout(id); }, [load]);
  useEffect(() => { if (!toast) return; const id = setTimeout(() => setToast(undefined), 5000); return () => clearTimeout(id); }, [toast]);
  async function addWater(amount_ml: number) { if (!summary || pending) return; const payload: WaterLogInsert = { id: newClientId(), log_date: summary.date, amount_ml }; setPending(true); setSummary({ ...summary, metrics: summary.metrics ? { ...summary.metrics, water_total_ml: summary.metrics.water_total_ml + amount_ml } : null }); try { const saved = await apiData<WaterLogRow>("/api/nutrition/water", { method: "POST", json: payload }); setToast({ message: `${amount_ml} ml registrados`, undo: () => void (async () => { setToast(undefined); await apiData(`/api/nutrition/water/${saved.id}`, { method: "DELETE" }); await load(); })() }); await load(); } catch (cause) { setToast({ message: cause instanceof Error ? cause.message : "Não foi possível registrar a água." }); await load(); } finally { setPending(false); } }
  function openMeal() { if (!summary || summary.next_action.kind !== "log_meal") return; const slot = summary.next_action.meal_slot; setEditing({ slot, values: { id: newClientId(), log_date: summary.date, meal_slot: slot, calories: 0, protein_g: 0, carbs_g: 0, fat_g: 0, description: null, is_completed: true } }); }
  async function saveWeight(weight_kg: number) { if (!summary) return; setPending(true); try { await apiData<WeightLogRow>("/api/nutrition/weight", { method: "POST", json: { logged_at: summary.date, weight_kg } }); setWeightOpen(false); setToast({ message: "Peso registrado" }); await load(); } catch (cause) { setToast({ message: cause instanceof Error ? cause.message : "Não foi possível registrar o peso." }); } finally { setPending(false); } }
  async function openMedication(id: string) { try { const response = await apiFetch<MedicationsResponse>("/api/medications"); setMedHelp(response.help ?? {}); setMedSevere(response.data.severe_recently); const item = response.data.items.find((entry) => entry.medication.id === id); if (item) setMedication(item); else setToast({ message: "Medicação não encontrada." }); } catch (cause) { setToast({ message: cause instanceof Error ? cause.message : "Não foi possível carregar a medicação." }); } }
  function runNextAction() { if (!summary) return; const action = summary.next_action; if (action.kind === "setup_profile") router.push("/alimentacao"); else if (action.kind === "log_meal") openMeal(); else if (action.kind === "drink_water") void addWater(action.suggested_ml); else if (action.kind === "log_weight") setWeightOpen(true); else if (action.kind === "log_medication") void openMedication(action.medication_id); else void addWater(250); }
  if (!summary) return <div className="space-y-3">{error ? <div className="rounded-2xl border border-danger-500/30 bg-danger-500/10 p-4 text-sm text-rose-200">{error} <button className="ml-2 underline" onClick={() => void load()}>Tentar novamente</button></div> : <><div className="h-6 w-52 animate-pulse rounded bg-white/10" /><div className="h-52 animate-pulse rounded-2xl bg-white/10" /><div className="h-28 animate-pulse rounded-2xl bg-white/10" /></>}</div>;
  const action = summary.next_action; const workout = training; const tip = summary.daily_tip;
  return <div className={`space-y-3 ${spacer}`}><header className="flex items-center justify-between gap-3"><h1 className="truncate text-sm font-semibold">{greeting(summary.now_time)}{summary.first_name ? `, ${summary.first_name}` : ""}</h1><time className="shrink-0 text-sm text-zinc-300" dateTime={summary.date}>{shortDate(summary.date)}</time></header><CalorieRemainingCard metrics={summary.metrics} aboveFold help={foodHelp} />
    <section data-above-fold="next-action" className="rounded-2xl border border-white/10 bg-white/10 p-4 shadow-xl backdrop-blur-md"><p className="text-sm font-semibold text-zinc-300">Agora</p><p className={`mt-1 text-lg font-bold ${action.kind === "log_meal" && action.overdue ? "text-warning-500" : "text-white"}`}>{actionText(summary)}</p>{summary.next_reminder ? <Link href="/lembretes" className="mt-2 block text-xs text-zinc-300 underline-offset-4 hover:underline">Próximo lembrete: {summary.next_reminder.title} · {summary.next_reminder.date === summary.date ? "hoje" : shortDate(summary.next_reminder.date)} {summary.next_reminder.time}</Link> : null}</section>
    {action.kind === "log_medication" ? <p className="rounded-xl border border-white/20 bg-white/5 p-3 text-sm text-zinc-200">{MEDICATION_DISCLAIMER}</p> : null}{medSevere || strongNotice ? <p role="alert" className="rounded-xl border border-danger-500/50 bg-danger-500/15 p-3 text-sm text-rose-200">{SEVERE_NOTICE}</p> : null}
    <section className="rounded-2xl border border-white/10 bg-white/5 p-4"><h2 className="font-bold">Treino de hoje</h2>{workout?.program ? <><p className="mt-1 text-sm text-zinc-200">{workout.next_workout?.title ?? "Programa conclu?do"} · {workout.program.title}{workout.next_workout?.estimated_minutes ? ` · ${workout.next_workout?.estimated_minutes} min` : ""}</p>{workout.done_today ? <span className="mt-2 inline-block rounded-full bg-success-500/20 px-3 py-1 text-xs font-semibold text-emerald-200">Feito hoje</span> : null}</> : <Link href="/treinos" className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-emerald-200">Escolher um programa</Link>}</section>
    {tip ? <Link href={`/dicas?tip=${tip.id}`} className="block rounded-2xl border border-white/10 bg-white/5 p-4"><h2 className="font-bold">Dica do dia</h2><p className="mt-1 text-sm">{tip.title}</p><p className="mt-1 text-xs text-zinc-300">{tip.category} · {tip.read_minutes} min de leitura</p></Link> : null}<div className="pt-2">{masterCards}</div>
    <BottomActionBar><Button data-primary-action={action.kind === "log_medication" ? "log-dose" : "next-action"} className="h-12 min-w-0 flex-1 bg-success-500 px-3 font-bold text-zinc-950 hover:bg-success-500/85" disabled={pending} onClick={runNextAction}>{pending ? <LoaderCircle className="animate-spin" aria-hidden /> : action.kind === "drink_water" || action.kind === "all_done" ? <Droplet aria-hidden /> : action.kind === "log_weight" ? <Scale aria-hidden /> : action.kind === "log_meal" ? <Utensils aria-hidden /> : action.kind === "log_medication" ? <HeartPulse aria-hidden /> : <Plus aria-hidden />}{action.kind === "all_done" ? "+250 ml" : action.kind === "log_medication" ? "Registrar aplicação" : actionText(summary)}</Button>{action.kind === "all_done" ? <Button variant="secondary" className="h-12 shrink-0 px-3 text-emerald-200" disabled={pending} onClick={() => void addWater(500)}>+500 ml</Button> : <Button data-primary-action="water-quick" variant="secondary" className="h-12 shrink-0 px-3 text-emerald-200" disabled={pending} onClick={() => void addWater(250)}>+250 ml</Button>}</BottomActionBar>
    <MealEditor userId={userId} editing={editing} onChange={setEditing} onClose={() => setEditing(undefined)} onChanged={load} help={foodHelp} /><WeightSheet open={weightOpen} initialWeight={summary.latest_weight_kg ?? 70} pending={pending} onClose={() => setWeightOpen(false)} onSave={(weight) => void saveWeight(weight)} /><MedicationLogSheet overview={medication} date={summary.date} help={medHelp} onClose={() => setMedication(null)} onSaved={async (strong) => { if (strong) setStrongNotice(true); await load(); }} />
    {toast ? <div role="status" className="fixed left-1/2 z-40 flex w-[calc(100%-2rem)] max-w-sm -translate-x-1/2 items-center justify-between gap-3 rounded-2xl border border-white/10 bg-zinc-900/95 p-3 text-sm shadow-2xl backdrop-blur-xl [bottom:calc(10rem+env(safe-area-inset-bottom))] md:bottom-24"><span>{toast.message}</span>{toast.undo ? <button className="min-h-11 shrink-0 font-semibold text-emerald-300" onClick={toast.undo}>Desfazer</button> : null}</div> : null}</div>;
}
