"use client";
import { useCallback, useEffect, useState, type ReactNode } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Droplet, LoaderCircle, Plus, Scale, Utensils } from "lucide-react";
import { CalorieRemainingCard } from "@/components/alimentacao/calorie-remaining-card";
import { MealEditor, MEAL_LABELS, type MealEditing } from "@/components/alimentacao/meal-editor";
import { WeightSheet } from "@/components/alimentacao/weight-sheet";
import { BottomActionBar, useBottomActionBarSpacer } from "@/components/ui/bottom-action-bar";
import { Button } from "@/components/ui/button";
import { apiData, apiFetch, newClientId } from "@/lib/api/client";
import type { DashboardSummary, MealLogRow, MealLogUpsert, WaterLogInsert, WaterLogRow, WeightLogRow } from "@/types/database";
function greeting(time: string) { const hour = Number(time.slice(0, 2)); return hour < 12 ? "Bom dia" : hour < 18 ? "Boa tarde" : "Boa noite"; }
function shortDate(date: string) { return new Intl.DateTimeFormat("pt-BR", { weekday: "short", day: "2-digit", month: "short", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`)); }
function actionText(summary: DashboardSummary) { const action = summary.next_action; if (action.kind === "setup_profile") return "Configure suas metas (2 min)"; if (action.kind === "log_meal") return `Registrar ${MEAL_LABELS[action.meal_slot]}${action.overdue ? " · atrasado" : ""}`; if (action.kind === "drink_water") return `Beber ${action.suggested_ml} ml — você está ${action.behind_ml} ml atrás do ritmo`; if (action.kind === "log_weight") return "Registrar peso da semana"; return "Tudo em dia"; }
export function DashboardExperience({ legacyCards }: { legacyCards: ReactNode }) {
  const router = useRouter();
  const spacer = useBottomActionBarSpacer();
  const [summary, setSummary] = useState<DashboardSummary>(); const [error, setError] = useState<string>(); const [pending, setPending] = useState(false); const [editing, setEditing] = useState<MealEditing>(); const [weightOpen, setWeightOpen] = useState(false); const [toast, setToast] = useState<{ message: string; undo?: () => void }>();
  const load = useCallback(async () => { try { setSummary((await apiFetch<DashboardSummary>("/api/dashboard/summary")).data); setError(undefined); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar o resumo."); } }, []);
  useEffect(() => { const id = setTimeout(() => void load(), 0); return () => clearTimeout(id); }, [load]);
  useEffect(() => { if (!toast) return; const id = setTimeout(() => setToast(undefined), 5000); return () => clearTimeout(id); }, [toast]);
  async function addWater(amount_ml: number) { if (!summary || pending) return; const payload: WaterLogInsert = { id: newClientId(), log_date: summary.date, amount_ml }; setPending(true); setSummary({ ...summary, metrics: summary.metrics ? { ...summary.metrics, water_total_ml: summary.metrics.water_total_ml + amount_ml } : null }); try { const saved = await apiData<WaterLogRow>("/api/nutrition/water", { method: "POST", json: payload }); setToast({ message: `${amount_ml} ml registrados`, undo: () => void (async () => { setToast(undefined); await apiData(`/api/nutrition/water/${saved.id}`, { method: "DELETE" }); await load(); })() }); await load(); } catch (cause) { setToast({ message: cause instanceof Error ? cause.message : "Não foi possível registrar a água." }); await load(); } finally { setPending(false); } }
  function openMeal() { if (!summary || summary.next_action.kind !== "log_meal") return; const slot = summary.next_action.meal_slot; setEditing({ slot, values: { id: newClientId(), log_date: summary.date, meal_slot: slot, calories: 0, protein_g: 0, carbs_g: 0, fat_g: 0, description: null, is_completed: true } }); }
  async function saveMeal(payload: MealLogUpsert) { setEditing(undefined); setPending(true); try { await apiData<MealLogRow[]>("/api/nutrition/meals", { method: "PUT", json: payload }); setToast({ message: "Refeição registrada" }); await load(); } catch (cause) { setToast({ message: cause instanceof Error ? cause.message : "Não foi possível salvar a refeição." }); } finally { setPending(false); } }
  async function saveWeight(weight_kg: number) { if (!summary) return; setPending(true); try { await apiData<WeightLogRow>("/api/nutrition/weight", { method: "POST", json: { logged_at: summary.date, weight_kg } }); setWeightOpen(false); setToast({ message: "Peso registrado" }); await load(); } catch (cause) { setToast({ message: cause instanceof Error ? cause.message : "Não foi possível registrar o peso." }); } finally { setPending(false); } }
  function runNextAction() { if (!summary) return; const action = summary.next_action; if (action.kind === "setup_profile") router.push("/alimentacao"); else if (action.kind === "log_meal") openMeal(); else if (action.kind === "drink_water") void addWater(action.suggested_ml); else if (action.kind === "log_weight") setWeightOpen(true); else void addWater(250); }
  if (!summary) return <div className="space-y-3">{error ? <div className="rounded-2xl border border-danger-500/30 bg-danger-500/10 p-4 text-sm text-rose-200">{error} <button className="ml-2 underline" onClick={() => void load()}>Tentar novamente</button></div> : <><div className="h-6 w-52 animate-pulse rounded bg-white/10" /><div className="h-52 animate-pulse rounded-2xl bg-white/10" /><div className="h-28 animate-pulse rounded-2xl bg-white/10" /></>}</div>;
  const action = summary.next_action;
  return <div className={`space-y-3 ${spacer}`}><header className="flex items-center justify-between gap-3"><h1 className="truncate text-sm font-semibold">{greeting(summary.now_time)}{summary.first_name ? `, ${summary.first_name}` : ""}</h1><time className="shrink-0 text-sm text-zinc-300" dateTime={summary.date}>{shortDate(summary.date)}</time></header><CalorieRemainingCard metrics={summary.metrics} aboveFold /><section data-above-fold="next-action" className="rounded-2xl border border-white/10 bg-white/10 p-4 shadow-xl backdrop-blur-md"><p className="text-sm font-semibold text-zinc-300">Agora</p><p className={`mt-1 text-lg font-bold ${action.kind === "log_meal" && action.overdue ? "text-warning-500" : "text-white"}`}>{actionText(summary)}</p>{summary.next_reminder ? <Link href="/lembretes" className="mt-2 block text-xs text-zinc-300 underline-offset-4 hover:underline">Próximo lembrete: {summary.next_reminder.title} · {summary.next_reminder.date === summary.date ? "hoje" : shortDate(summary.next_reminder.date)} {summary.next_reminder.time}</Link> : null}</section><div className="pt-2">{legacyCards}</div><BottomActionBar><Button data-primary-action="next-action" className="h-12 min-w-0 flex-1 bg-success-500 px-3 font-bold text-zinc-950 hover:bg-success-500/85" disabled={pending} onClick={runNextAction}>{pending ? <LoaderCircle className="animate-spin" aria-hidden /> : action.kind === "drink_water" || action.kind === "all_done" ? <Droplet aria-hidden /> : action.kind === "log_weight" ? <Scale aria-hidden /> : action.kind === "log_meal" ? <Utensils aria-hidden /> : <Plus aria-hidden />}{action.kind === "all_done" ? "+250 ml" : actionText(summary)}</Button>{action.kind === "all_done" ? <Button variant="secondary" className="h-12 shrink-0 px-3 text-emerald-200" disabled={pending} onClick={() => void addWater(500)}>+500 ml</Button> : <Button data-primary-action="water-quick" variant="secondary" className="h-12 shrink-0 px-3 text-emerald-200" disabled={pending} onClick={() => void addWater(250)}>+250 ml</Button>}</BottomActionBar><MealEditor editing={editing} onChange={setEditing} onClose={() => setEditing(undefined)} onSave={(payload) => void saveMeal(payload)} /><WeightSheet open={weightOpen} pending={pending} onClose={() => setWeightOpen(false)} onSave={(weight) => void saveWeight(weight)} />{toast ? <div role="status" className="fixed left-1/2 z-40 flex w-[calc(100%-2rem)] max-w-sm -translate-x-1/2 items-center justify-between gap-3 rounded-2xl border border-white/10 bg-zinc-900/95 p-3 text-sm shadow-2xl backdrop-blur-xl [bottom:calc(10rem+env(safe-area-inset-bottom))] md:bottom-24"><span>{toast.message}</span>{toast.undo ? <button className="min-h-11 shrink-0 font-semibold text-emerald-300" onClick={toast.undo}>Desfazer</button> : null}</div> : null}</div>;
}
