"use client";
import { useCallback, useEffect, useState } from "react";
import { HeartPulse, Plus, Scale } from "lucide-react";
import { BottomActionBar, useBottomActionBarSpacer } from "@/components/ui/bottom-action-bar";
import { Button } from "@/components/ui/button";
import { HelpHint } from "@/components/ui/help-hint";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Stepper } from "@/components/ui/stepper";
import { WeightSheet } from "@/components/alimentacao/weight-sheet";
import { apiData, apiFetch } from "@/lib/api/client";
import { getTodayIsoDate } from "@/lib/date";
import { MEDICATION_DISCLAIMER, type BodyMeasurementRow, type BodyMeasurementUpsert, type HelpTooltipMap, type MedicationOverview, type MedicationsResponse, type ProgressResponse, type WeightLogRow } from "@/types/database";
import { EFFECT_LABELS, MedicationLogSheet, SEVERE_NOTICE, SITE_LABELS } from "./medication-log-sheet";
import { MedicationFormSheet } from "./medication-form-sheet";

function formatDate(date: string) { return new Intl.DateTimeFormat("pt-BR", { weekday: "short", day: "2-digit", month: "2-digit", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`)); }
const MEASURES = [{ key: "waist_cm", label: "Cintura", fallback: 80 }, { key: "hip_cm", label: "Quadril", fallback: 95 }, { key: "chest_cm", label: "Peito", fallback: 90 }, { key: "arm_cm", label: "Braço", fallback: 30 }, { key: "thigh_cm", label: "Coxa", fallback: 50 }] as const;
const DISPLAY_MEASURES = [...MEASURES.map(({ key, label }) => ({ key, label, unit: "cm" })), { key: "neck_cm", label: "Pescoço", unit: "cm" }, { key: "body_fat_pct", label: "Gordura corporal", unit: "%" }] as const;

export function HealthDashboard() {
  const today = getTodayIsoDate(); const spacer = useBottomActionBarSpacer();
  const [tab, setTab] = useState<"medication" | "progress">("medication");
  const [medications, setMedications] = useState<MedicationsResponse>(); const [medHelp, setMedHelp] = useState<Partial<HelpTooltipMap>>({});
  const [progress, setProgress] = useState<ProgressResponse>(); const [progressHelp, setProgressHelp] = useState<Partial<HelpTooltipMap>>({});
  const [days, setDays] = useState<30 | 90 | 180>(30); const [error, setError] = useState<string>();
  const [logOverview, setLogOverview] = useState<MedicationOverview | null>(null); const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<MedicationOverview | null>(null);
  const [measureOpen, setMeasureOpen] = useState(false); const [weightOpen, setWeightOpen] = useState(false);
  const [strongNotice, setStrongNotice] = useState(false);
  const loadMedications = useCallback(async () => { try { const result = await apiFetch<MedicationsResponse>("/api/medications"); setMedications(result.data); setMedHelp(result.help ?? {}); setError(undefined); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar medicações."); } }, []);
  const loadProgress = useCallback(async () => { try { const result = await apiFetch<ProgressResponse>(`/api/progress?days=${days}`); setProgress(result.data); setProgressHelp(result.help ?? {}); setError(undefined); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar o progresso."); } }, [days]);
  useEffect(() => { const id = setTimeout(() => void loadMedications(), 0); return () => clearTimeout(id); }, [loadMedications]);
  useEffect(() => { if (tab !== "progress") return; const id = setTimeout(() => void loadProgress(), 0); return () => clearTimeout(id); }, [tab, loadProgress]);
  async function changeActive(item: MedicationOverview) { try { await apiData(`/api/medications/${item.medication.id}`, { method: "PATCH", json: { is_active: !item.medication.is_active } }); await loadMedications(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível atualizar."); } }
  async function deleteMedication(item: MedicationOverview) { if (!window.confirm(`Excluir ${item.medication.name}? Esta ação apaga todo o histórico de aplicações.`)) return; try { await apiData(`/api/medications/${item.medication.id}`, { method: "DELETE" }); await loadMedications(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível excluir."); } }
  async function undoLog(id: string) { try { await apiData(`/api/medications/logs/${id}`, { method: "DELETE" }); await loadMedications(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível desfazer."); } }
  const due = medications?.items.find((item) => item.medication.is_active && item.due_today && !item.taken_today);
  const latest = progress?.measurements.at(-1);
  return <div className={`space-y-4 ${spacer}`}><header className="flex items-center gap-2"><HeartPulse className="size-6 text-emerald-300" aria-hidden /><h1 className="text-xl font-black">Saúde</h1>{tab === "medication" ? <HelpHint help={medHelp["route.medicacao"]} /> : <HelpHint help={progressHelp["route.progresso"]} />}</header><div className="grid grid-cols-2 gap-2" role="tablist" aria-label="Saúde"><button role="tab" aria-selected={tab === "medication"} className={`min-h-12 rounded-xl border font-semibold ${tab === "medication" ? "border-brand-500 bg-brand-500/20 text-white" : "border-white/20 text-zinc-300"}`} onClick={() => setTab("medication")}>Medicação</button><button role="tab" aria-selected={tab === "progress"} className={`min-h-12 rounded-xl border font-semibold ${tab === "progress" ? "border-brand-500 bg-brand-500/20 text-white" : "border-white/20 text-zinc-300"}`} onClick={() => setTab("progress")}>Progresso</button></div>
    {error ? <p role="alert" className="rounded-xl border border-danger-500/30 bg-danger-500/10 p-3 text-sm text-rose-200">{error} <button className="underline" onClick={() => void (tab === "medication" ? loadMedications() : loadProgress())}>Tentar novamente</button></p> : null}
    {tab === "medication" ? <div className="space-y-4"><p className="rounded-xl border border-white/20 bg-white/5 p-3 text-sm text-zinc-200">{MEDICATION_DISCLAIMER}</p>{medications?.severe_recently || strongNotice ? <p role="alert" className="rounded-xl border border-danger-500/50 bg-danger-500/15 p-3 text-sm font-semibold text-rose-200">{SEVERE_NOTICE}</p> : null}
      {!medications ? <p className="text-sm text-zinc-300">Carregando medicações…</p> : !medications.items.length ? <section className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-bold">Acompanhe sua prescrição</h2><p className="mt-2 text-sm text-zinc-300">Registre a medicação definida com seu médico, as aplicações e como você se sentiu.</p></section> : <><div className="space-y-3">{medications.items.map((item) => { const med = item.medication; return <section key={med.id} className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-start justify-between gap-2"><div><h2 className="font-bold">{med.name}</h2><p className="mt-1 text-sm text-zinc-300">{med.dose_amount == null ? "Dose não informada" : `${med.dose_amount} ${med.dose_unit} · ${med.frequency}${med.days_of_week?.length ? ` · ${med.days_of_week.map((day) => ["dom", "seg", "ter", "qua", "qui", "sex", "sáb"][day]).join(", ")}` : ""}`}</p></div><button type="button" className="min-h-11 text-sm text-emerald-200" onClick={() => { setEditing(item); setFormOpen(true); }}>Editar</button></div><p className={`mt-2 text-sm font-semibold ${!med.is_active ? "text-zinc-300" : item.taken_today ? "text-emerald-300" : item.due_today ? "text-warning-500" : "text-zinc-200"}`}>{!med.is_active ? "Pausada" : item.taken_today ? "Aplicado hoje ✓" : item.due_today ? "Hoje é dia de aplicar" : item.next_due_date ? `Próxima: ${formatDate(item.next_due_date)}` : "Sem próxima data prevista"}</p>{item.due_today && !item.taken_today && med.is_active ? <button type="button" className="mt-2 min-h-11 text-sm font-semibold text-emerald-200" onClick={() => setLogOverview(item)}>Registrar aplicação</button> : null}<div className="mt-2 flex gap-4 border-t border-white/10 pt-2"><button type="button" className="min-h-11 text-xs text-zinc-300" onClick={() => void changeActive(item)}>{med.is_active ? "Pausar" : "Reativar"}</button><button type="button" className="min-h-11 text-xs text-rose-300" onClick={() => void deleteMedication(item)}>Excluir</button></div></section>; })}</div>
      {medications.side_effect_summary.length ? <section className="rounded-2xl border border-white/10 p-4"><h2 className="font-bold">Efeitos registrados (30 dias)</h2><div className="mt-2 flex flex-wrap gap-2">{medications.side_effect_summary.map((item) => <span key={item.effect} className="rounded-full border border-white/20 px-3 py-2 text-xs text-zinc-200">{EFFECT_LABELS[item.effect]} · {item.count}</span>)}</div></section> : null}
      <section className="rounded-2xl border border-white/10 p-4"><h2 className="font-bold">Histórico recente</h2>{medications.recent_logs.length ? medications.recent_logs.map((log) => <div key={log.id} className="flex items-center justify-between gap-2 border-b border-white/10 py-2 text-sm"><span>{formatDate(log.log_date)} · {medications.items.find((item) => item.medication.id === log.medication_id)?.medication.name ?? "Medicação"}{log.injection_site ? ` · ${SITE_LABELS[log.injection_site]}` : ""}{log.side_effects.length ? ` · ${log.side_effects.map((effect) => EFFECT_LABELS[effect]).join(", ")}` : ""}</span><button className="min-h-11 shrink-0 text-rose-300" onClick={() => void undoLog(log.id)}>Desfazer</button></div>) : <p className="mt-2 text-sm text-zinc-300">Nenhuma aplicação registrada.</p>}</section></>}</div> : <ProgressTab progress={progress} days={days} setDays={setDays} help={progressHelp} onWeight={() => setWeightOpen(true)} />}
    <BottomActionBar>{tab === "medication" ? <><Button data-primary-action={due ? "log-dose" : undefined} className="h-12 flex-1 bg-success-500 font-bold text-zinc-950 hover:bg-success-500/85" onClick={() => due ? setLogOverview(due) : (setEditing(null), setFormOpen(true))}>{due ? "Registrar aplicação" : "Cadastrar medicação"}</Button>{medications?.items.length ? <Button variant="secondary" className="h-12" aria-label="Cadastrar outra medicação" onClick={() => { setEditing(null); setFormOpen(true); }}><Plus aria-hidden /></Button> : null}</> : <><Button data-primary-action="log-measurements" className="h-12 flex-1 bg-success-500 font-bold text-zinc-950 hover:bg-success-500/85" onClick={() => setMeasureOpen(true)}>Registrar medidas</Button><Button variant="secondary" className="h-12" onClick={() => setWeightOpen(true)}><Scale aria-hidden /> Peso</Button></>}</BottomActionBar>
    <MedicationLogSheet overview={logOverview} date={today} help={medHelp} onClose={() => setLogOverview(null)} onSaved={async (strong) => { if (strong) setStrongNotice(true); await loadMedications(); }} />
    <MedicationFormSheet open={formOpen} medication={editing?.medication} help={medHelp} onClose={() => setFormOpen(false)} onSaved={loadMedications} />
    <MeasurementSheet open={measureOpen} latest={latest} help={progressHelp} date={today} onClose={() => setMeasureOpen(false)} onSaved={loadProgress} />
    <WeightSheet open={weightOpen} initialWeight={progress?.weights.at(-1)?.weight_kg ?? 70} onClose={() => setWeightOpen(false)} onSave={(weight) => void (async () => { try { await apiData<WeightLogRow>("/api/nutrition/weight", { method: "POST", json: { logged_at: today, weight_kg: weight } }); setWeightOpen(false); await loadProgress(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível registrar peso."); } })()} />
  </div>;
}

function ProgressTab({ progress, days, setDays, help, onWeight }: { progress?: ProgressResponse; days: 30 | 90 | 180; setDays: (days: 30 | 90 | 180) => void; help: Partial<HelpTooltipMap>; onWeight: () => void }) {
  const [point, setPoint] = useState<number | null>(null);
  if (!progress) return <p className="text-sm text-zinc-300">Carregando progresso…</p>;
  const weights = progress.weights; const values = weights.map((item) => item.weight_kg); const low = Math.floor(Math.min(...(values.length ? values : [0])) - (values.length ? 2 : 0)); const high = Math.ceil(Math.max(...(values.length ? values : [1])) + (values.length ? 2 : 0)); const span = Math.max(1, high - low);
  const coords = weights.map((item, i) => ({ x: 42 + i * (290 / Math.max(1, weights.length - 1)), y: 145 - (item.weight_kg - low) / span * 120 }));
  const change = progress.weight_change_kg; const waist = progress.waist_change_cm;
  return <div className="space-y-4"><div className="flex gap-2">{([30, 90, 180] as const).map((value) => <button key={value} type="button" onClick={() => setDays(value)} className={`min-h-11 rounded-xl border px-4 text-sm font-semibold ${days === value ? "border-brand-500 bg-brand-500/20" : "border-white/20"}`}>{value} dias</button>)}</div>
    <section className="rounded-2xl border border-white/10 bg-white/5 p-4"><h2 className="font-bold">Peso</h2><p className={`mt-1 text-2xl font-black ${change != null && change < 0 ? "text-emerald-300" : "text-white"}`}>{change == null ? "Sem variação ainda" : `${change > 0 ? "+" : ""}${change.toFixed(1)} kg`}</p>{weights.length ? <><svg viewBox="0 0 350 170" className="mt-2 w-full" role="img" aria-label="Evolução do peso">{[0, 1, 2, 3].map((i) => { const y = 25 + i * 40; return <g key={i}><line x1="42" x2="336" y1={y} y2={y} stroke="#52525b" strokeDasharray="3 4" /><text x="2" y={y + 4} fill="#d4d4d8" fontSize="12">{(high - i * span / 3).toFixed(0)}</text></g>; })}<polyline points={coords.map(({ x, y }) => `${x},${y}`).join(" ")} fill="none" stroke="#34d399" strokeWidth="3" />{coords.map(({ x, y }, i) => <g key={i} role="button" tabIndex={0} aria-label={`${formatDate(weights[i].date)}: ${weights[i].weight_kg} kg`} onClick={() => setPoint(i)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") setPoint(i); }}><circle cx={x} cy={y} r="23" fill="transparent" /><circle cx={x} cy={y} r="8" fill="#34d399" stroke="#09090b" strokeWidth="2" /></g>)}</svg>{point != null && weights[point] ? <p className="text-sm text-emerald-200">{formatDate(weights[point].date)} · {weights[point].weight_kg} kg</p> : null}</> : <button className="mt-2 min-h-11 text-sm text-emerald-200" onClick={onWeight}>Registrar primeiro peso</button>}</section>
    <section className="rounded-2xl border border-white/10 bg-white/5 p-4"><h2 className="font-bold">Medidas corporais</h2><p className={`mt-1 text-lg font-bold ${waist != null && waist < 0 ? "text-emerald-300" : "text-white"}`}>Cintura: {waist == null ? "sem variação" : `${waist > 0 ? "+" : ""}${waist.toFixed(1)} cm`}</p>{progress.measurements.length ? progress.measurements.slice(-5).reverse().map((row) => <p key={row.id} className="border-b border-white/10 py-2 text-sm text-zinc-200">{formatDate(row.logged_at)} · {DISPLAY_MEASURES.filter((item) => row[item.key] != null).map((item) => `${item.label} ${row[item.key]} ${item.unit}`).join(" · ")}</p>) : <p className="mt-2 text-sm text-zinc-300">Registre uma medida para acompanhar a evolução.</p>}</section>
    <section className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-1"><h2 className="font-bold">Constância (30 dias)</h2><HelpHint help={help["route.progresso"]} /></div><div className="mt-3 grid grid-cols-2 gap-3">{([{ label: "Dias com refeições", value: progress.consistency.meal_days }, { label: "Meta de água", value: progress.consistency.water_goal_days }, { label: "Treinos", value: progress.consistency.workouts }, { label: "Aplicações", value: progress.consistency.medication_doses }]).map((item) => <div key={item.label}><p className="text-3xl font-black text-emerald-300">{item.value}</p><p className="text-xs text-zinc-300">{item.label}</p></div>)}</div></section>
  </div>;
}

function MeasurementSheet({ open, latest, date, help, onClose, onSaved }: { open: boolean; latest?: BodyMeasurementRow; date: string; help: Partial<HelpTooltipMap>; onClose: () => void; onSaved: () => void | Promise<void> }) { if (!open) return null; return <MeasurementContent latest={latest} date={date} help={help} onClose={onClose} onSaved={onSaved} />; }
function MeasurementContent({ latest, date, help, onClose, onSaved }: { latest?: BodyMeasurementRow; date: string; help: Partial<HelpTooltipMap>; onClose: () => void; onSaved: () => void | Promise<void> }) {
  const [values, setValues] = useState<Record<string, number>>({}); const [touched, setTouched] = useState<string[]>([]); const [pending, setPending] = useState(false); const [error, setError] = useState<string>();
  const save = async () => { if (!touched.length) { setError("Toque em uma medida antes de salvar."); return; } const payload: BodyMeasurementUpsert = { logged_at: date }; for (const key of touched) Object.assign(payload, { [key]: values[key] }); setPending(true); setError(undefined); try { await apiData("/api/progress/measurements", { method: "PUT", json: payload }); await onSaved(); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar."); } finally { setPending(false); } };
  return <Sheet open onOpenChange={(next) => { if (!next) onClose(); }}><SheetContent side="bottom" className="max-h-[94dvh] overflow-y-auto rounded-t-3xl border-white/10 bg-zinc-950 p-4 pb-[max(1rem,env(safe-area-inset-bottom))] sm:left-1/2 sm:max-w-xl sm:-translate-x-1/2"><SheetHeader className="px-0"><SheetTitle>Registrar medidas</SheetTitle></SheetHeader><div className="space-y-3">{MEASURES.map((item) => <div key={item.key}><div className="flex items-end gap-1"><div className="flex-1"><Stepper value={values[item.key] ?? latest?.[item.key] ?? item.fallback} onChange={(value) => { setValues((current) => ({ ...current, [item.key]: value })); setTouched((current) => current.includes(item.key) ? current : [...current, item.key]); }} step={0.5} min={1} max={300} unit="cm" label={item.label} /></div>{item.key === "waist_cm" ? <HelpHint help={help["body_measurements.waist_cm"]} /> : null}</div>{touched.includes(item.key) ? <p className="text-xs text-emerald-200">Será registrado</p> : null}</div>)}</div>{error ? <p role="alert" className="mt-2 text-sm text-rose-300">{error}</p> : null}<div className="sticky bottom-0 -mx-4 mt-4 bg-zinc-950 px-4 pt-3"><Button data-primary-action="log-measurements" className="h-12 w-full bg-success-500 font-bold text-zinc-950 hover:bg-success-500/85" disabled={pending || !touched.length} onClick={() => void save()}>{pending ? "Salvando…" : "Salvar medidas"}</Button></div></SheetContent></Sheet>;
}

